[project]
name = "misc-utils"
version = "0.1.0"
description = "some utilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "webloc>=2020.12.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src/py"]
